config/urls.py
from apps.df_cart.views import cart
from apps.df_goods.views import goods
from apps.df_order.views import order
from apps.df_users.views import user


def init_url(app):
    # 蓝图注册
    app.register_blueprint(goods)
    app.register_blueprint(user)
    app.register_blueprint(cart)
    app.register_blueprint(order)

apps/df_goods/views.py
from datetime import datetime

from flask import render_template, Blueprint, request, session, jsonify

from apps.df_goods.models import Goods, Comment
from apps.df_users.models import User

from config.exts import db

goods = Blueprint('goods', __name__)

# 用户首页显示商品


@goods.route('/')
def index():
    cookie = request.cookies.get('token')
    user_id = session.get(cookie)
    goods = Goods.query.all()
    if user_id:
        user = User.query.filter_by(id=user_id).first()
        context = {
            'user': user,
            'goods': goods
        }
        return render_template('goods/index.html', **context)
    else:
        context = {
            'goods': goods
        }
        return render_template('goods/index.html', **context)

# 商品详情


@goods.route('/<good_id>/')
def good_datail(good_id):
    cookie = request.cookies.get('token')
    user_id = session.get(cookie)
    good = Goods.query.filter_by(id=good_id).first()
    comments = Comment.query.filter_by(gid=good_id).all()
    if user_id:
        user = User.query.filter_by(id=user_id).first()
        context = {
            'goods': good,
            'comment_num': len(comments),
            'user': user,
            'comments': comments
        }
        return render_template('goods/good_detail.html', **context)
    else:
        context = {
            'goods': good,
            'comment_num': len(comments),
            'comments': comments,
            'user': None
        }
        return render_template('goods/good_detail.html', **context)

# 商品评论


@goods.route('/goods/comment', methods=['GET', 'POST'])
def goods_comment():
    token = request.cookies.get('token')
    user_id = session.get(token)
    if request.method == 'POST':
        comment_time = datetime.now().strftime('%Y:%m:%d %H:%M:%S')
        content = request.form.get('content')
        gid = request.form.get('gid')

        comment = Comment()

        comment.content = content
        comment.uid = user_id
        comment.gid = gid
        comment.cdate = comment_time

        db.session.add(comment)
        db.session.commit()

        user_comment = Comment.query.filter_by(content=content).first()
        # user_comment = Comment.query.all()[0]
        data = {
            'status': 200,
            'username': user_comment.user.name,
            'img_url': user_comment.user.avatar_url,
            'content': user_comment.content,
            'comment_time': str(user_comment.cdate)
        }

        return jsonify(data)

# 商品浏览量


@goods.route('/goods/click_counts')
def goods_click_counts():
    goods_id = request.args.get('gid')
    goods = Goods.query.filter_by(id=goods_id).first()

    goods.click_counts += 1  # 商品详情页没刷新一次浏览量+1
    db.session.add(goods)
    db.session.commit()

    return jsonify('200')

# 检索商品-模糊查询


@goods.route('/search', methods=['GET'])
def search_goods():
    if request.method == 'GET':
        kw = request.args.get('kw')

        goods = Goods.query.filter(Goods.title.like("%" + kw + "%")).all()

        # return jsonify('200')
        return render_template('goods/search_show.html', goods=goods)

apps/df_users/views.py
import random
import uuid

from flask import Blueprint, render_template, request, jsonify, json, Response, redirect, url_for, session

from apps.df_users.models import User
from common.aliyun_yzm import sendsms
from common.check_login import check_login
from common.img_code import return_img_code
from config.exts import db

user = Blueprint('user', __name__)

# 用户注册


@user.route('/user/register', methods=["GET", "POST"])
def register():
    if request.method == 'GET':
        return render_template('user/register.html')
    else:
        # 获取用户填写的表单信息
        username = request.form.get('username')
        password = request.form.get('password')
        re_password = request.form.get('re_password')
        mobile = request.form.get('mobile')
        real_name = request.form.get('real_name')
        id_card = request.form.get('id_card')
        print(username, password, re_password, mobile, real_name, id_card)
        # 判断用户输入的密码
        if password == re_password:
            user1 = User.query.filter_by(name=username).first()
            if user1:
                data = {
                    "msg": '用户名已存在'
                }
                return jsonify(data)
            else:
                user = User()
                user.name = username
                # 传递的用户密码加密
                user.password = password
                user.mobile = mobile
                user.real_name = real_name
                user.id_card = id_card

                # 数据库实现添加
                db.session.add(user)
                db.session.commit()

                return jsonify(200)

# 用户登录


@user.route('/user/login', methods=['GET', 'POST'])
def login():
    # 实现判读用户是否登录以及跳转
    next_url = ''
    try:
        next_url = request.full_path.split('?next_url=')[1]
    except Exception as e:
        print(e)
    if request.method == 'GET':
        return render_template('user/login.html', next_url=next_url)
    else:
        username = request.form.get('username')
        password = request.form.get('password')

        user = User.query.filter_by(name=username).first()
        if user:
            # 验证用户密码
            if user.verify_password(password):
                # 生成token存到cookie中
                token = str(uuid.uuid4())
                # 将user.id 添加到session中
                session[token] = user.id
                if len(next_url) == 0:
                    response = redirect(url_for('goods.index'))
                    # 向页面添加cookie
                    response.set_cookie('token', token)
                    return response
                else:
                    print(next_url)
                    response = redirect(next_url)
                    response.set_cookie('token', token)
                    return response
            else:
                return render_template('user/login.html', msg='用户名或密码错误')

#用户退出


@user.route('/user/logout', methods=["GET"])
def lg():
    cookie = request.cookies.get('token')

    session.pop(cookie)

    return redirect(url_for('goods.index'))

#获取图片验证码


@user.route('/user/get_img_code', methods=['GET'])
def get_img_code():
    img_path, num = return_img_code()
    data = {
        'img_path': img_path.split('.')[1] + '.png',
        'num': num
    }
    return jsonify(data)

# 获取手机验证码


@user.route('/user/get_phone_code', methods=['GET'])
def get_phone_code():
    username = request.args.get('username')
    phone = request.args.get('phone')
    user = User.query.filter_by(name=username).first()
    if user:
        if user.mobile == phone:
            code = dict()
            code['code'] = str(random.randint(100000, 999999))
            if phone:
                # sendsms(phone, code)

                data = {
                    'status': 200,
                    'code': code['code']
                }
                return jsonify(data)
        else:
            data = {
                'status': 402,
                'msg': '请使用注册的手机号获取验证码'
            }
            return jsonify(data)

# 用户的个人信息


@user.route('/user/user_info/', methods=['GET'])
def user_info():
    token = request.cookies.get('token')
    user_id = session.get(token)
    if user_id:
        user = User.query.filter_by(id=user_id).first()
        return render_template('user/user_info.html', user=user)
    else:
        next_url = request.path
        return redirect('/user/login?next_url=' + next_url)

# 用户地址


@user.route('/user/user_addr/', methods=["GET"])
def user_addr():
    if request.method == "GET":
        token = request.cookies.get('token')
        user_id = session.get(token)
        if user_id:
            user = User.query.filter_by(id=user_id).first()
            return render_template('user/user_addr.html', user=user)


@user.route('/user/add_addr', methods=['GET', 'POST'])
def add_addr():
    if request.method == 'POST':
        token = request.cookies.get('token')
        user_id = session.get(token)

        user = User.query.filter_by(id=user_id).first()

        addr = request.form.get('addr')

        user.addr = addr

        db.session.add(user)

        db.session.commit()

        return redirect(url_for('user.user_addr'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    <script src="/static/jquery-3.3.1/jquery-3.3.1.min.js"></script>
    <script src="/static/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css">
    <style>
        * {
            margin: 0;
            padding: 0;
        }

        html, body {
            width: 100%;
            {#height: 100%;#}
        }

        a {
            color: black;
            text-decoration: none;
        }

        a:hover {
            text-decoration: none;
            color: black;
        }
        #content{
            width: 100%;
            clear: both;
        }
        #footer {
            background-color: #d2d2d2;
            width: 100%;
            height: 270px;
            text-align: center;
            clear: both;
            margin-top: 50px;
        }
        .footer_title{
            margin-top: 10px;
        }
        .s_f{
            margin-left: 120px;
        }
    </style>
    {% block css %}

    {% endblock %}
</head>
<body>
<div id="header">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('goods.index') }}">首页</a></li>
{#                    <li><a href="#">分类</a></li>#}
                </ul>
                <form class="s_f navbar-form navbar-left" action="{{ url_for('goods.search_goods') }}" method="get">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="" name="kw">
                    </div>
                    <button type="submit" class="btn btn-default">搜索</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('cart.add_cart') }}">购物车</a></li>
                    <li><a href="{{ url_for('user.user_info') }}">个人中心</a></li>
                    {% if user %}
                        <li><a href="#">{{ user.name }}</a></li>
                        <li><a href="{{ url_for('user.lg') }}">退出</a></li>
                    {% else %}
                        <li><a href="{{ url_for('user.login') }}">登录</a></li>
                        <li><a href="{{ url_for('user.register') }}">注册</a></li>
                    {% endif %}


                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
</div>

<div id="content">
    {% block content %}

    {% endblock %}
</div>
<div id="footer">
    <address class="footer_title">
        <strong>义升陶瓷, Inc.</strong><br>
        <span class="glyphicon glyphicon-map-marker" style="color: rgb(140, 140, 60);"> 地址：</span>国贸广场国贸街24号<br>
        江西，景德镇 <br>
        <abbr title="Phone"><span class="glyphicon glyphicon-phone-alt" style="color: rgb(140, 140, 60);"> 联系电话：</span></abbr>
        13979850474
    </address>
    <address>
        <a href="mailto:#"><span class="glyphicon glyphicon-envelope" style="color: rgb(140, 140, 60);"> 邮件：</span>1163902851@qq.com</a>
    </address>
    <div id="footer_div2" pull-right>
        <figure><img src="../static/image/wechat.jpg" style="width: 100px; height: 100px;">
            <figcaption>微信联系我们</figcaption>
        </figure>
    </div>
</div>
</body>
{% block js %}

{% endblock %}
</html>