config/urls.py
from apps.df_cart.views import cart
from apps.df_goods.views import goods
from apps.df_order.views import order
from apps.df_users.views import user


def init_url(app):
    # 蓝图注册
    app.register_blueprint(goods)
    app.register_blueprint(user)
    app.register_blueprint(cart)
    app.register_blueprint(order)

apps/df_order/views.py
import json
import time
import random
from io import StringIO
from datetime import datetime

import qrcode
from flask import Blueprint, render_template, jsonify, request, g, session, redirect, url_for
from sqlalchemy import and_, text

from apps.df_cart.models import ShopCart
from apps.df_goods.models import Goods
from apps.df_order.models import Order
from apps.df_users.models import User
from config.exts import db

order = Blueprint('order', __name__)


# 获取订单的信心


@order.route('/order/getOrderInfo', methods=['GET', 'POST'])
def get_order_info():
    if request.method == 'POST':
        data = request.form.get('aaa')
        cart_list = data.split(',')
        session['cart'] = cart_list
        return jsonify('200')


# 购物车立即付款获取购物车的内容


@order.route('/order/orderInfo', methods=['GET', 'POST'])
def order_info():
    token = request.cookies.get('token')
    user_id = session.get(token)
    user = User.query.filter_by(id=user_id).first()
    carts = []
    try:
        for cart_id in session.get('cart'):
            cart = ShopCart.query.filter_by(id=cart_id).first()
            carts.append(cart)
        context = {
            'carts': carts,
            'user': user
        }
        return render_template('order/order_info.html', **context)
    except:
        return redirect(url_for('cart.add_cart'))


# 支付订单


@order.route('/order/pay_order')
def pay_order():
    # 判断支付的订单数量1 or 多
    order_id = request.args.get('order_id', None)
    if order_id is None:
        url_path = request.full_path
        res = url_path.split('?')[1].split('&')[0:-1]
        num = 0
        for i in range(1, len(res) + 1):
            id = 'oid_' + str(i)
            print(id)
            oid = request.args.get(id)
            print(oid)
            order = Order.query.filter_by(id=oid).first()
            num += order.total_money
        context = {
            'num': num,
            'kw': url_path.split('?')[1],
            'status': 1
        }

        return render_template('order/pay_order.html', **context)
    else:
        order = Order.query.filter_by(id=order_id).first()
        context = {
            'num': order.total_money,
            'order_id': order_id,
            'status': 0
        }

        return render_template('order/pay_order.html', **context)


# 支付成功跳转的页面


@order.route('/order/pay_success')
def pay_success():
    order_id = request.args.get('order_id', None)
    if order_id is None:
        url_path = request.full_path
        res = url_path.split('?')[1].split('&')[0:-1]
        for i in range(1, len(res) + 1):
            id = 'oid_' + str(i)
            oid = request.args.get(id)

            order = Order.query.filter_by(id=oid).first()
            order.state = 1

            db.session.add(order)
            db.session.commit()
        return render_template('order/pay_success.html')
    else:
        order = Order.query.filter_by(id=order_id).first()

        order.state = 1

        db.session.add(order)
        db.session.commit()
        order_id_list = []
        return render_template('order/pay_success.html', order_id_list=order_id_list)


# 提交订单


@order.route('/order/submit_order', methods=['GET', 'POST'])
def submit_order():
    host = request.host
    order_id = request.args.get('order_id')
    print(order_id)
    # 从订单中心支付
    if order_id:
        order = Order.query.filter_by(id=order_id).first()
        # 生成二维码保存，返回到页面中
        url = 'http://' + host + '/order/pay_order?order_id=' + order_id
        print(url)
        img = qrcode.make(url)
        img.save('./static/pay_qrcode/pay.png')
        order_id_list = []
        context = {
            'num': order.total_money,
            'img_src': '/static/pay_qrcode/pay.png' + '?t=' + str(time.time()),
            'order_id': order_id,
            'order_id_list_len': len(order_id_list)
        }
        return render_template('order/pay_page.html', **context)
    else:
        # 从提交订单页面支付
        num = 0
        token = request.cookies.get('token')
        user_id = session.get(token)
        order_id_list = []
        print(session.get('cart'))
        for cart_id in session.get('cart'):
            cart = ShopCart.query.filter_by(id=cart_id).first()
            order_time = datetime.now().strftime('%Y:%m:%d %H:%M:%S')
            order = Order()

            order.count = cart.counts
            order.gid = cart.gid
            order.uid = user_id
            order.state = 0
            order.total_money = cart.counts * cart.goods.price
            order.ordertime = order_time

            db.session.add(order)
            db.session.commit()

            order_id = Order.query.filter(and_(Order.count == cart.counts, Order.gid == cart.gid, Order.uid == user_id,
                                               Order.ordertime == order_time)).first()

            order_id_list.append(order_id.id)
            goods = Goods.query.filter_by(id=cart.gid).first()
            goods.counts -= cart.counts

            db.session.add(goods)

            db.session.commit()

            db.session.delete(cart)

            db.session.commit()
        url = 'http://' + host + '/order/pay_order?'
        for i in range(1, len(order_id_list) + 1):
            url += 'oid_' + str(i) + '=' + str(order_id_list[i - 1]) + '&'

        img = qrcode.make(url)
        img.save('./static/pay_qrcode/pay.png')

        # session.pop('cart')
        context = {
            'num': order.total_money,
            'img_src': '/static/pay_qrcode/pay.png' + '?t=' + str(time.time()),
            'order_id': order_id,
            'order_id_list_len': len(order_id_list),
            'order_id_list': order_id_list
        }

        return render_template('order/pay_page.html', **context)


# 我的订单-全部订单


@order.route('/order/my_order/', methods=['GET', 'POST'])
def order_list():
    print(session.get('cart'))
    if request.method == 'GET':
        url_path = 'all'
        page = int(request.args.get('page', 1))
        token = request.cookies.get('token')
        user_id = session.get(token)
        if user_id:
            user = User.query.filter_by(id=user_id).first()
            # 实现分页
            paginate = Order.query.filter_by(uid=user_id).order_by(text('-ordertime')).paginate(page, 4)
            orders = paginate.items

            context = {
                'user': user,
                'paginate': paginate,
                'orders': orders,
                'url_path': url_path
            }
            return render_template('user/order_list.html', **context)


# 待支付订单


@order.route('/order/wait_pay/')
def wait_pay():
    if request.method == 'GET':
        url_path = 'pay'
        page = int(request.args.get('page', 1))
        token = request.cookies.get('token')
        user_id = session.get(token)
        if user_id:
            user = User.query.filter_by(id=user_id).first()
            paginate = Order.query.filter(and_(Order.uid == user_id, Order.state == 0)).order_by(
                text('-ordertime')).paginate(page, 4)
            orders = paginate.items

            context = {
                'user': user,
                'paginate': paginate,
                'orders': orders,
                'url_path': url_path
            }
            return render_template('user/order_list.html', **context)


# 待收货订单


@order.route('/order/wait_recevi/')
def wait_recevi():
    if request.method == 'GET':
        url_path = 'recevi'
        page = int(request.args.get('page', 1))
        token = request.cookies.get('token')
        user_id = session.get(token)
        if user_id:
            user = User.query.filter_by(id=user_id).first()
            paginate = Order.query.filter(and_(Order.uid == user_id, Order.state == 1)).order_by(
                text('-ordertime')).paginate(page, 4)
            orders = paginate.items
            context = {
                'user': user,
                'paginate': paginate,
                'orders': orders,
                'url_path': url_path
            }
            return render_template('user/order_list.html', **context)


# 确认收货


@order.route('/order/sure', methods=['GET', 'POST'])
def sure_order():
    order_id = request.args.get('order_id')

    order = Order.query.filter_by(id=order_id).first()

    order.state = 2

    db.session.add(order)
    db.session.commit()

    return redirect(url_for('order.order_list'))


# 判断订单是否支付


@order.route('/order/judge_status')
def judge_status():
    order_id = request.args.get('order_id')

    order = Order.query.filter_by(id=order_id).first()
    print(order)
    if order.state == 1:
        return jsonify('200')
    else:
        return jsonify('201')

templates/order/order_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>订单结算页</title>
    <script src="/static/jquery-3.3.1/jquery-3.3.1.min.js"></script>
    <style>
        * {
            margin: 0;
            padding: 0;
        }

        html, body {
            width: 100%;
            height: 100%;
        }

        #app {
            width: 70%;
            margin: 20px auto;
        }

        .consignee_info, .pay {
            width: 80%;
            min-width: 700px;
            height: 100px;
            border: 1px solid #dddddd;
            margin-bottom: 5px;
        }

        .user_info {
            margin-left: 40px;
            width: 93%;
            height: 30px;
            line-height: 30px;
            padding-left: 10px;
        }

        .user_info:hover {
            background-color: #e4b9c0;
        }

        .online_pay {
            width: 70px;
            height: 28px;
            margin-left: 20px;
            border: 2px solid red;
        }

        .detailed_list {
            width: 80%;
            min-height: 160px;
            min-width: 700px;
            border: 1px solid #dddddd;
        }

        .detail {
            margin: 10px 0 10px 20px;
            height: 110px;
        }

        .goods_img_name {
            float: left;
            width: 300px;
        }

        .goods_img {
            width: 100px;
            height: 100px;
            float: left;
            margin-right: 5px;
        }

        .goods_price {
            float: left;
            width: 100px;
            height: 30px;
            margin-top: 30px;
            margin-left: 50px;
        }

        .goods_num {
            float: left;
            width: 50px;
            height: 30px;
            margin-top: 30px;
            margin-left: 130px;
        }

        .submit_order {
            width: 80%;
            min-width: 700px;
            height: 60px;
            text-align: right;
            border: 1px solid #d2d2d2;
            background-color: #d2d2d2;
        }

        .price {
            color: red;
            margin-right: 20px;
        }

        #submit_order {
            width: 120px;
            height: 40px;
            background-color: red;
            color: white;
            border: 0;
            font-size: 18px;
            cursor: pointer;
        }
    </style>
</head>
<body>
<div id="app">
    <h3 style="margin-bottom: 20px">结算页</h3>
    <p style="margin-bottom: 20px">填写并核对订单信息</p>
    <div class="consignee_info">
        <p>收货人信息</p>
        <p class="user_info">
            <span>{{ user.name }}</span>&nbsp;&nbsp;
            <span>{{ user.addr }}</span>&nbsp;&nbsp;
            <span>{{ user.mobile }}</span>
        </p>

    </div>
    <div class="pay">
        <p>支付方式</p>
        <button type="button" class="online_pay">在线支付</button>
    </div>
    <div class="detailed_list">
        <p>送货清单</p>
        {% for cart in carts %}
            <div class="detail">
                <div class="goods_img_name">
                    <img class="goods_img" src="{{ cart.goods.index_image_url }}" alt=""/>
                    <span>{{ cart.goods.title }}</span>
                </div>
                <div class="goods_price">
                    <b>¥</b><span class="unit_price">{{ cart.goods.price }}</span>
                </div>
                <div class="goods_num">
                    <b>x</b><span class="num">{{ cart.counts }}</span>
                </div>
            </div>
            <hr style="clear: both; position: relative; top: 5px;"/>
        {% endfor %}
    </div>
    <div class="submit_order">
        <p style="height: 30px">
            <span style="margin-right: 50px">应付总金额:</span><b>¥</b><span class="price"></span>
        </p>
        <p>
            <span>寄送至:</span><span>{{ user.addr }}</span>
            <span>收货人:</span>{{ user.name }}&nbsp;&nbsp;&nbsp;<span style="margin-right: 20px">{{ user.mobile }}</span>
        </p>
    </div>
    <div style="width: 80%; min-width: 700px; text-align: right">
        <button id="submit_order">提交订单</button>
    </div>


</div>

</body>
<script>
    $(function () {
        let total_price = 0;
        $('.detail').each(function () {
            let unit_price = $(this).find('.unit_price').html();
            let num = $(this).find('.num').html();

            total_price += Number(unit_price) * Number(num);
        });
        $('.price').html(total_price);
        $('#submit_order').click(function () {
            let url = 'http://' + window.location.host + '/order/submit_order';
            window.open(url, target='_parent')
        })
    })
</script>
</html>

templates/order/pay_order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="/static/jquery-3.3.1/jquery-3.3.1.min.js"></script>
    <style>
        button {
            width: 120px;
            height: 40px;
            border: 0;
            background-color: red;
            color: white;
            margin: 10px 0 0 10px;
        }
    </style>
</head>
<body>
支付金额：{{ num }}<br/>
{% if status == 1 %}
    <a href="{{ url_for('order.pay_success') }}?{{ kw }}" hidden>
        <span class="pay">支付</span>
    </a>
{% else %}
    <a href="{{ url_for('order.pay_success') }}?order_id={{ order_id }}" hidden>
        <span class="pay">支付</span>
    </a>
{% endif %}

<button onclick="pay_click()">立即支付</button>
</body>
<script>
    function pay_click() {
        $('.pay').click()
    }
</script>
</html>

templates/order/pay_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="/static/jquery-3.3.1/jquery-3.3.1.min.js"></script>
    <style>
        * {
            margin: 0;
            padding: 0;
        }

        html, body {
            width: 100%;
            height: 100%;
        }

        #app {
            width: 80%;
            min-width: 800px;
            height: 600px;
            margin: 10px auto;
            border: 1px solid #dddddd;
        }

        .alipay, .chatpay {
            width: 100px;
            height: 35px;
            background-color: white;
            border: 1px solid black;
            margin: 20px 0 0 20px;
        }

        .alipay {
            border: 2px solid red;
        }

        .pay {
            width: 120px;
            height: 40px;
            position: relative;
            top: 20px;
            left: 200px;
            background-color: red;
            color: white;
            font-size: 18px;
            border: 0;
        }

        .img_qrcode {
            width: 100px;
            height: 100px;
        }
    </style>
</head>
<body>
<div id="app">
    <div class="pay_money">
        <p>支付金额: <span style="color: red">{{ num }}</span><span>元</span></p>
        {% if order_id_list_len == 0 %}
        <span class="order_id" hidden>{{ order_id }}</span>
            {% else %}
            <span class="order_id" hidden>{{ order_id_list[0] }}</span>

        {% endif %}

    </div>
    <div class="pay_mode">
        <p>选择支付方式</p>
        <button type="button" class="alipay">支付宝</button>
        <button type="button" class="chatpay">微信</button>
    </div>
    <div>
        <img class="img_qrcode" src="{{ img_src }}" alt=""/>
    </div>
    <div class="">
        <button class="pay">立即支付</button>
    </div>
</div>
</body>
<script>
    $(function () {
        $('.alipay').click(function () {
            $('.alipay').css({
                'border': '2px solid red'
            });
            $('.chatpay').css({
                'border': '1px solid black'
            })
        });
        $('.chatpay').click(function () {
            $('.alipay').css({
                'border': '1px solid black'
            });
            $('.chatpay').css({
                'border': '2px solid red'
            })
        });
    })
</script>
<script>
    let timer = setInterval("request_order_status()", 6000);
    function request_order_status(){
        let order_id = $('.order_id').html();
        console.log(order_id)
        $.get(
            'http://' + window.location.host + '/order/judge_status',
            {
                'order_id': order_id
            },
            function (data) {
                if (data == 200) {
                    clearInterval(timer);
                    let r = confirm('查看我的订单');

                    if (r == true) {
                        window.open('http://' + window.location.host + '/order/my_order', target='_parent')
                    } else {
                        window.open('http://' + window.location.host + '/', target='_parent')
                    }
                }
            }
        )
    }

</script>
</html>

templates/order/pay_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>支付成功</p>
</body>
</html>