config/urls.py
from apps.df_cart.views import cart
from apps.df_goods.views import goods
from apps.df_order.views import order
from apps.df_users.views import user


def init_url(app):
    # 蓝图注册
    app.register_blueprint(goods)
    app.register_blueprint(user)
    app.register_blueprint(cart)
    app.register_blueprint(order)

apps/df_goods/views.py
from datetime import datetime

from flask import render_template, Blueprint, request, session, jsonify

from apps.df_goods.models import Goods, Comment
from apps.df_users.models import User

from config.exts import db

goods = Blueprint('goods', __name__)

# 用户首页显示商品


@goods.route('/')
def index():
    cookie = request.cookies.get('token')
    user_id = session.get(cookie)
    goods = Goods.query.all()
    if user_id:
        user = User.query.filter_by(id=user_id).first()
        context = {
            'user': user,
            'goods': goods
        }
        return render_template('goods/index.html', **context)
    else:
        context = {
            'goods': goods
        }
        return render_template('goods/index.html', **context)

# 商品详情


@goods.route('/<good_id>/')
def good_datail(good_id):
    cookie = request.cookies.get('token')
    user_id = session.get(cookie)
    good = Goods.query.filter_by(id=good_id).first()
    comments = Comment.query.filter_by(gid=good_id).all()
    if user_id:
        user = User.query.filter_by(id=user_id).first()
        context = {
            'goods': good,
            'comment_num': len(comments),
            'user': user,
            'comments': comments
        }
        return render_template('goods/good_detail.html', **context)
    else:
        context = {
            'goods': good,
            'comment_num': len(comments),
            'comments': comments,
            'user': None
        }
        return render_template('goods/good_detail.html', **context)

# 商品评论


@goods.route('/goods/comment', methods=['GET', 'POST'])
def goods_comment():
    token = request.cookies.get('token')
    user_id = session.get(token)
    if request.method == 'POST':
        comment_time = datetime.now().strftime('%Y:%m:%d %H:%M:%S')
        content = request.form.get('content')
        gid = request.form.get('gid')

        comment = Comment()

        comment.content = content
        comment.uid = user_id
        comment.gid = gid
        comment.cdate = comment_time

        db.session.add(comment)
        db.session.commit()

        user_comment = Comment.query.filter_by(content=content).first()
        # user_comment = Comment.query.all()[0]
        data = {
            'status': 200,
            'username': user_comment.user.name,
            'img_url': user_comment.user.avatar_url,
            'content': user_comment.content,
            'comment_time': str(user_comment.cdate)
        }

        return jsonify(data)

# 商品浏览量


@goods.route('/goods/click_counts')
def goods_click_counts():
    goods_id = request.args.get('gid')
    goods = Goods.query.filter_by(id=goods_id).first()

    goods.click_counts += 1  # 商品详情页没刷新一次浏览量+1
    db.session.add(goods)
    db.session.commit()

    return jsonify('200')

# 检索商品-模糊查询


@goods.route('/search', methods=['GET'])
def search_goods():
    if request.method == 'GET':
        kw = request.args.get('kw')

        goods = Goods.query.filter(Goods.title.like("%" + kw + "%")).all()

        # return jsonify('200')
        return render_template('goods/search_show.html', goods=goods)

apps/df_order/views.py
import json
import time
import random
from io import StringIO
from datetime import datetime

import qrcode
from flask import Blueprint, render_template, jsonify, request, g, session, redirect, url_for
from sqlalchemy import and_, text

from apps.df_cart.models import ShopCart
from apps.df_goods.models import Goods
from apps.df_order.models import Order
from apps.df_users.models import User
from config.exts import db

order = Blueprint('order', __name__)


# 获取订单的信心


@order.route('/order/getOrderInfo', methods=['GET', 'POST'])
def get_order_info():
    if request.method == 'POST':
        data = request.form.get('aaa')
        cart_list = data.split(',')
        session['cart'] = cart_list
        return jsonify('200')


# 购物车立即付款获取购物车的内容


@order.route('/order/orderInfo', methods=['GET', 'POST'])
def order_info():
    token = request.cookies.get('token')
    user_id = session.get(token)
    user = User.query.filter_by(id=user_id).first()
    carts = []
    try:
        for cart_id in session.get('cart'):
            cart = ShopCart.query.filter_by(id=cart_id).first()
            carts.append(cart)
        context = {
            'carts': carts,
            'user': user
        }
        return render_template('order/order_info.html', **context)
    except:
        return redirect(url_for('cart.add_cart'))


# 支付订单


@order.route('/order/pay_order')
def pay_order():
    # 判断支付的订单数量1 or 多
    order_id = request.args.get('order_id', None)
    if order_id is None:
        url_path = request.full_path
        res = url_path.split('?')[1].split('&')[0:-1]
        num = 0
        for i in range(1, len(res) + 1):
            id = 'oid_' + str(i)
            print(id)
            oid = request.args.get(id)
            print(oid)
            order = Order.query.filter_by(id=oid).first()
            num += order.total_money
        context = {
            'num': num,
            'kw': url_path.split('?')[1],
            'status': 1
        }

        return render_template('order/pay_order.html', **context)
    else:
        order = Order.query.filter_by(id=order_id).first()
        context = {
            'num': order.total_money,
            'order_id': order_id,
            'status': 0
        }

        return render_template('order/pay_order.html', **context)


# 支付成功跳转的页面


@order.route('/order/pay_success')
def pay_success():
    order_id = request.args.get('order_id', None)
    if order_id is None:
        url_path = request.full_path
        res = url_path.split('?')[1].split('&')[0:-1]
        for i in range(1, len(res) + 1):
            id = 'oid_' + str(i)
            oid = request.args.get(id)

            order = Order.query.filter_by(id=oid).first()
            order.state = 1

            db.session.add(order)
            db.session.commit()
        return render_template('order/pay_success.html')
    else:
        order = Order.query.filter_by(id=order_id).first()

        order.state = 1

        db.session.add(order)
        db.session.commit()
        order_id_list = []
        return render_template('order/pay_success.html', order_id_list=order_id_list)


# 提交订单


@order.route('/order/submit_order', methods=['GET', 'POST'])
def submit_order():
    host = request.host
    order_id = request.args.get('order_id')
    print(order_id)
    # 从订单中心支付
    if order_id:
        order = Order.query.filter_by(id=order_id).first()
        # 生成二维码保存，返回到页面中
        url = 'http://' + host + '/order/pay_order?order_id=' + order_id
        print(url)
        img = qrcode.make(url)
        img.save('./static/pay_qrcode/pay.png')
        order_id_list = []
        context = {
            'num': order.total_money,
            'img_src': '/static/pay_qrcode/pay.png' + '?t=' + str(time.time()),
            'order_id': order_id,
            'order_id_list_len': len(order_id_list)
        }
        return render_template('order/pay_page.html', **context)
    else:
        # 从提交订单页面支付
        num = 0
        token = request.cookies.get('token')
        user_id = session.get(token)
        order_id_list = []
        print(session.get('cart'))
        for cart_id in session.get('cart'):
            cart = ShopCart.query.filter_by(id=cart_id).first()
            order_time = datetime.now().strftime('%Y:%m:%d %H:%M:%S')
            order = Order()

            order.count = cart.counts
            order.gid = cart.gid
            order.uid = user_id
            order.state = 0
            order.total_money = cart.counts * cart.goods.price
            order.ordertime = order_time

            db.session.add(order)
            db.session.commit()

            order_id = Order.query.filter(and_(Order.count == cart.counts, Order.gid == cart.gid, Order.uid == user_id,
                                               Order.ordertime == order_time)).first()

            order_id_list.append(order_id.id)
            goods = Goods.query.filter_by(id=cart.gid).first()
            goods.counts -= cart.counts

            db.session.add(goods)

            db.session.commit()

            db.session.delete(cart)

            db.session.commit()
        url = 'http://' + host + '/order/pay_order?'
        for i in range(1, len(order_id_list) + 1):
            url += 'oid_' + str(i) + '=' + str(order_id_list[i - 1]) + '&'

        img = qrcode.make(url)
        img.save('./static/pay_qrcode/pay.png')

        # session.pop('cart')
        context = {
            'num': order.total_money,
            'img_src': '/static/pay_qrcode/pay.png' + '?t=' + str(time.time()),
            'order_id': order_id,
            'order_id_list_len': len(order_id_list),
            'order_id_list': order_id_list
        }

        return render_template('order/pay_page.html', **context)


# 我的订单-全部订单


@order.route('/order/my_order/', methods=['GET', 'POST'])
def order_list():
    print(session.get('cart'))
    if request.method == 'GET':
        url_path = 'all'
        page = int(request.args.get('page', 1))
        token = request.cookies.get('token')
        user_id = session.get(token)
        if user_id:
            user = User.query.filter_by(id=user_id).first()
            # 实现分页
            paginate = Order.query.filter_by(uid=user_id).order_by(text('-ordertime')).paginate(page, 4)
            orders = paginate.items

            context = {
                'user': user,
                'paginate': paginate,
                'orders': orders,
                'url_path': url_path
            }
            return render_template('user/order_list.html', **context)


# 待支付订单


@order.route('/order/wait_pay/')
def wait_pay():
    if request.method == 'GET':
        url_path = 'pay'
        page = int(request.args.get('page', 1))
        token = request.cookies.get('token')
        user_id = session.get(token)
        if user_id:
            user = User.query.filter_by(id=user_id).first()
            paginate = Order.query.filter(and_(Order.uid == user_id, Order.state == 0)).order_by(
                text('-ordertime')).paginate(page, 4)
            orders = paginate.items

            context = {
                'user': user,
                'paginate': paginate,
                'orders': orders,
                'url_path': url_path
            }
            return render_template('user/order_list.html', **context)


# 待收货订单


@order.route('/order/wait_recevi/')
def wait_recevi():
    if request.method == 'GET':
        url_path = 'recevi'
        page = int(request.args.get('page', 1))
        token = request.cookies.get('token')
        user_id = session.get(token)
        if user_id:
            user = User.query.filter_by(id=user_id).first()
            paginate = Order.query.filter(and_(Order.uid == user_id, Order.state == 1)).order_by(
                text('-ordertime')).paginate(page, 4)
            orders = paginate.items
            context = {
                'user': user,
                'paginate': paginate,
                'orders': orders,
                'url_path': url_path
            }
            return render_template('user/order_list.html', **context)


# 确认收货


@order.route('/order/sure', methods=['GET', 'POST'])
def sure_order():
    order_id = request.args.get('order_id')

    order = Order.query.filter_by(id=order_id).first()

    order.state = 2

    db.session.add(order)
    db.session.commit()

    return redirect(url_for('order.order_list'))


# 判断订单是否支付


@order.route('/order/judge_status')
def judge_status():
    order_id = request.args.get('order_id')

    order = Order.query.filter_by(id=order_id).first()
    print(order)
    if order.state == 1:
        return jsonify('200')
    else:
        return jsonify('201')

apps/df_users/views.py
import random
import uuid

from flask import Blueprint, render_template, request, jsonify, json, Response, redirect, url_for, session

from apps.df_users.models import User
from common.aliyun_yzm import sendsms
from common.check_login import check_login
from common.img_code import return_img_code
from config.exts import db

user = Blueprint('user', __name__)

# 用户注册


@user.route('/user/register', methods=["GET", "POST"])
def register():
    if request.method == 'GET':
        return render_template('user/register.html')
    else:
        # 获取用户填写的表单信息
        username = request.form.get('username')
        password = request.form.get('password')
        re_password = request.form.get('re_password')
        mobile = request.form.get('mobile')
        real_name = request.form.get('real_name')
        id_card = request.form.get('id_card')
        print(username, password, re_password, mobile, real_name, id_card)
        # 判断用户输入的密码
        if password == re_password:
            user1 = User.query.filter_by(name=username).first()
            if user1:
                data = {
                    "msg": '用户名已存在'
                }
                return jsonify(data)
            else:
                user = User()
                user.name = username
                # 传递的用户密码加密
                user.password = password
                user.mobile = mobile
                user.real_name = real_name
                user.id_card = id_card

                # 数据库实现添加
                db.session.add(user)
                db.session.commit()

                return jsonify(200)

# 用户登录


@user.route('/user/login', methods=['GET', 'POST'])
def login():
    # 实现判读用户是否登录以及跳转
    next_url = ''
    try:
        next_url = request.full_path.split('?next_url=')[1]
    except Exception as e:
        print(e)
    if request.method == 'GET':
        return render_template('user/login.html', next_url=next_url)
    else:
        username = request.form.get('username')
        password = request.form.get('password')

        user = User.query.filter_by(name=username).first()
        if user:
            # 验证用户密码
            if user.verify_password(password):
                # 生成token存到cookie中
                token = str(uuid.uuid4())
                # 将user.id 添加到session中
                session[token] = user.id
                if len(next_url) == 0:
                    response = redirect(url_for('goods.index'))
                    # 向页面添加cookie
                    response.set_cookie('token', token)
                    return response
                else:
                    print(next_url)
                    response = redirect(next_url)
                    response.set_cookie('token', token)
                    return response
            else:
                return render_template('user/login.html', msg='用户名或密码错误')

#用户退出


@user.route('/user/logout', methods=["GET"])
def lg():
    cookie = request.cookies.get('token')

    session.pop(cookie)

    return redirect(url_for('goods.index'))

#获取图片验证码


@user.route('/user/get_img_code', methods=['GET'])
def get_img_code():
    img_path, num = return_img_code()
    data = {
        'img_path': img_path.split('.')[1] + '.png',
        'num': num
    }
    return jsonify(data)

# 获取手机验证码


@user.route('/user/get_phone_code', methods=['GET'])
def get_phone_code():
    username = request.args.get('username')
    phone = request.args.get('phone')
    user = User.query.filter_by(name=username).first()
    if user:
        if user.mobile == phone:
            code = dict()
            code['code'] = str(random.randint(100000, 999999))
            if phone:
                # sendsms(phone, code)

                data = {
                    'status': 200,
                    'code': code['code']
                }
                return jsonify(data)
        else:
            data = {
                'status': 402,
                'msg': '请使用注册的手机号获取验证码'
            }
            return jsonify(data)

# 用户的个人信息


@user.route('/user/user_info/', methods=['GET'])
def user_info():
    token = request.cookies.get('token')
    user_id = session.get(token)
    if user_id:
        user = User.query.filter_by(id=user_id).first()
        return render_template('user/user_info.html', user=user)
    else:
        next_url = request.path
        return redirect('/user/login?next_url=' + next_url)

# 用户地址


@user.route('/user/user_addr/', methods=["GET"])
def user_addr():
    if request.method == "GET":
        token = request.cookies.get('token')
        user_id = session.get(token)
        if user_id:
            user = User.query.filter_by(id=user_id).first()
            return render_template('user/user_addr.html', user=user)


@user.route('/user/add_addr', methods=['GET', 'POST'])
def add_addr():
    if request.method == 'POST':
        token = request.cookies.get('token')
        user_id = session.get(token)

        user = User.query.filter_by(id=user_id).first()

        addr = request.form.get('addr')

        user.addr = addr

        db.session.add(user)

        db.session.commit()

        return redirect(url_for('user.user_addr'))

templates/user/order_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>订单列表</title>
    <script src="/static/jquery-3.3.1/jquery-3.3.1.min.js"></script>
    <style>
        * {
            margin: 0;
            padding: 0;
        }

        html, body {
            width: 100%;
        {#height: 100%;#} background-color: #d2d2d2;
        }

        .header {
            width: 100%;
            min-width: 800px;
            height: 20px;
            background-color: whitesmoke;
        }

        a {
            color: black;
            text-decoration: none;
        }

        a:hover {
            color: black;
            text-decoration: none;
        }

        .return_index {
            margin-left: 20%;
            color: black;
            font-size: 14px;
            line-height: 20px;
        }

        .user_lg {
            margin-left: 60%;
            color: black;
            font-size: 14px;
            line-height: 20px;
        }

        #content {
            width: 80%;
            min-width: 1000px;
            height: 100%;
            margin: 10px auto;
        {#border: 1px solid red;#} background-color: whitesmoke;
            display: flex;
        }

        .content_left {

        }

        .user_info_ul {
            width: 10%;
            min-width: 120px;
            height: 100%;
            margin: 0 0 0 10px;
            padding-top: 10px;
        }

        .user_info_li {
            list-style: none;
            width: 100px;
            height: 25px;
        }

        .content_right {
            width: 100%;
            height: 800px;
        {#border: 1px solid red;#}
        }

        .my_order_list {
            width: 100%;
            height: 40px;
            background-color: white;
            margin: 10px 0 10px 0;
            line-height: 40px;
            font-size: 18px;
        }

        .my_order_list > span {
            margin-left: 20px;
        }

        .s {
            width: 100%;
            height: 20px;
            background-color: white;
            font-size: 14px;
        }

        .all_order, .wait_pay, .wait_recevi {
            display: inline-block;
            margin-right: 15px;
        }

        .all_order {
            margin-left: 10px;
            border-bottom: 2px solid red;
        }
        .paginate{
            text-align: right;
            margin-right: 20px;
        }
        .all_order:hover, .wait_pay:hover, .wait_recevi:hover {
            color: red;
        }

        .all_order_content, .wait_pay_content, .wait_recevi_content {
            margin: 10px 0 0 0;
        }

        .order_detail {
            width: 98%;
            height: 120px;
            margin: 10px 0 10px 5px;
            background-color: white;
        }

        .order_name_img {
            width: 300px;
            height: 100px;
            float: left;
            margin: 10px 0 10px 10px;
        }

        .order_img {
            width: 100px;
            height: 100px;
            float: left;
        }

        .order_num {
            width: 150px;
            height: 100px;
            line-height: 100px;
            float: left;
        }

        .order_peoper {
            width: 150px;
            height: 100px;
            line-height: 100px;
            float: left;
        }

        .order_total_price {
            width: 150px;
            height: 100px;
            line-height: 100px;
            float: left;
        }

        .order_status {
            width: 60px;
            height: 100px;
            line-height: 80px;
            float: left;
        }

        .pay, .sure {
            width: 60px;
            height: 30px;
            border: 0;
            background-color: red;
            color: white;
            position: relative;
            top: -50px;
            left: -6px;
            cursor: pointer;
        }

        #footer {
            background-color: #dddddd;
            width: 100%;
            height: 260px;
            text-align: center;
            position: relative;
            top: 80px;
            clear: both;
        }

        .footer_title {
            margin-top: 10px;
        }
    </style>
</head>
<body>
<div id="app">
    <p class="header">
        <span class="return_index"><a href="{{ url_for('goods.index') }}">返回首页</a></span>
        <span class="user_lg"><a href="{{ url_for('user.lg') }}">退出</a> </span>
    </p>
    <div id="content">
        <div class="content_left">
            <ul class="user_info_ul">
                <li class="user_info_li"><a href="{{ url_for('user.user_info') }}">个人信息</a></li>
                <li class="user_info_li"><a href="{{ url_for('order.order_list') }}">我的订单</a></li>
                <li class="user_info_li"><a href="{{ url_for('user.user_addr') }}">收货地址</a></li>

            </ul>
        </div>
        <div class="content_right">
            <p class="my_order_list">
                <span>我的订单</span>
            </p>
            <div id="header_classify">
                <p class="s">
                    <span class="all_order"><a href="{{ url_for('order.order_list') }}">全部订单</a> </span>
                    <span class="wait_pay"><a href="{{ url_for('order.wait_pay') }}">待支付</a> </span>
                    <span class="wait_recevi"><a href="{{ url_for('order.wait_recevi') }}">待收货</a> </span>
                </p>
            </div>
            <div class="all_order_content">
{#            我的订单实现分页#}
                {% for order in orders %}
                    <span>订单时间：</span><span>{{ order.ordertime }}</span>
                    <div class="order_detail">

                        <div class="order_name_img">
                            <img class="order_img" src="{{ order.goods.index_image_url }}" alt=""/>
                            <span class="order_title">{{ order.goods.title }}</span>
                        </div>
                        <div class="order_num">
                            <span>x</span><span>{{ order.count }}</span>
                        </div>
                        <div class="order_peoper">
                            <span>{{ order.user.name }}</span>
                        </div>
                        <div class="order_total_price">
                            <span>¥</span><span>{{ order.total_money }}</span>
                        </div>
                        <div class="order_status">
                            {% if order.state == 0 %}
                                <span>待支付</span>
                                <span class="order_id" hidden>{{ order.id }}</span>
                                <button class="pay">去支付</button>
                            {% elif order.state == 1 %}
                                <span>待收货</span>
                                <a href="{{ url_for('order.sure_order') }}?order_id={{ order.id }}" hidden><span class="a_sure">确认收货</span></a>
                                <button class="sure">确认收货</button>
                            {% else %}
                                <span>已完成</span>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
{# 分页内容以及跳转#}
            <div class="paginate">
            当前页数：{{ paginate.page }}
                总页数：{{ paginate.pages }}
                一共有{{ paginate.total }}条数据
            <span class="url_path" hidden>{{ url_path }}</span>
                {% if url_path == 'all' %}
                    {% if paginate.has_prev %}
                        <a href="{{ url_for('order.order_list') }}?page={{ paginate.prev_num }}">上一页</a>
                    {% endif %}
                    页码：
                    {% for i in paginate.iter_pages() %}
                        <a href="{{ url_for('order.order_list') }}?page={{ i }}">{{ i }}</a>
                    {% endfor %}

                    {% if paginate.has_next %}
                        <a href="{{ url_for('order.order_list') }}?page={{ paginate.next_num }}">下一页</a>
                    {% endif %}
                {% elif url_path == 'pay' %}
                    {% if paginate.has_prev %}
                        <a href="{{ url_for('order.wait_pay') }}?page={{ paginate.prev_num }}">上一页</a>
                    {% endif %}
                    页码：
                    {% for i in paginate.iter_pages() %}
                        <a href="{{ url_for('order.wait_pay') }}?page={{ i }}">{{ i }}</a>
                    {% endfor %}

                    {% if paginate.has_next %}
                        <a href="{{ url_for('order.wait_pay') }}?page={{ paginate.next_num }}">下一页</a>
                    {% endif %}
                {% else %}
                    {% if paginate.has_prev %}
                        <a href="{{ url_for('order.wait_recevi') }}?page={{ paginate.prev_num }}">上一页</a>
                    {% endif %}
                    页码：
                    {% for i in paginate.iter_pages() %}
                        <a href="{{ url_for('order.wait_recevi') }}?page={{ i }}">{{ i }}</a>
                    {% endfor %}

                    {% if paginate.has_next %}
                        <a href="{{ url_for('order.wait_recevi') }}?page={{ paginate.next_num }}">下一页</a>
                    {% endif %}
                {% endif %}
            </div>



            </div>

        </div>
    </div>
</div>
<div id="footer">
    <address class="footer_title">
        <strong>义升陶瓷, Inc.</strong><br>
        <span class="glyphicon glyphicon-map-marker" style="color: rgb(140, 140, 60);"> 地址：</span>国贸广场国贸街24号<br>
        江西，景德镇 <br>
        <abbr title="Phone"><span class="glyphicon glyphicon-phone-alt" style="color: rgb(140, 140, 60);"> 联系电话：</span></abbr>
        13979850474
    </address>
    <address>
        <a href="mailto:#"><span class="glyphicon glyphicon-envelope" style="color: rgb(140, 140, 60);"> 邮件：</span>1163902851@qq.com</a>
    </address>
    <div id="footer_div2" pull-right>
        <figure><img src="/static/image/wechat.jpg" style="width: 100px; height: 100px;">
            <figcaption>微信联系我们</figcaption>
        </figure>
    </div>
</div>
</body>
<script>
    $(function () {
        let url_path = $('.url_path').html();
        if (url_path == 'all') {
            $('.all_order').css({
                'border-bottom': '2px solid red',
            })
        } else if (url_path == 'pay') {
            $('.wait_pay').css({
                'border-bottom': '2px solid red',
            });
            $('.all_order').css({
                'border-bottom': '0',
                'color': 'black'
            });
            $('.wait_recevi').css({
                'border-bottom': '0',
                'color': 'black'
            })
        } else {
            $('.wait_recevi').css({
                'border-bottom': '2px solid red',
            });
            $('.wait_pay').css({
                'border-bottom': '0',
                'color': 'black'
            });
            $('.all_order').css({
                'border-bottom': '0',
                'color': 'black'
            });
        }
        $('.sure').click(function () {
            $(this).parent().find('.a_sure').click()
        });
        $('.pay').click(function () {
            let order_id = $(this).parent().find('.order_id').html();
            console.log(order_id);

            let url = 'http://' + window.location.host + '/order/submit_order?order_id=' + order_id;
            window.open(url, target = '_parent')
        })
    })
</script>
</html>